language: python
python:
  - "{{cookiecutter.minimum_python_version}}"

branches:
  only:
    - main

cache:
  pip: true
  directories:
    - "$HOME/.cache/"
    - "$HOME/virtualenv/"

before_install:
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
  - export PATH="$HOME/.poetry/bin:${PATH}"
  - rm poetry.lock
 
install:
  - make ci-install

script:
  - make ci-script

after_success:
  - bash <(curl -s https://codecov.io/bash) -y .ci/codecov.yml
