.PHONY: help Makefile docs tests

# ------------------------------------------------------------------------------------ #
#                                    Initialization                                    #
#																																										   #
#                                         init                                         #
# ------------------------------------------------------------------------------------ #
init:
	@pip install --upgrade pip
	@pip install poetry
	@poetry install
